name: "Validate Gradle Wrapper"
on: [push, pull_request]

  validation:
    name: "Validation"
    runs-on: ubuntu-latest

      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1